/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721AUpgradeableSol from "./ERC721AUpgradeable.sol";
export type { erc721AUpgradeableSol };
import type * as extensions from "./extensions";
export type { extensions };
export type { IERC721AUpgradeable } from "./IERC721AUpgradeable";
